logging:
  level:
    root: INFO
spring:
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
server:
  servlet:
    context-path: /mytfg
project:
  jwt:
    signKey: WzROun12eUiDvko3UrJ74gNeJz2TWEWPMTh6DxyE8HWXIf4hETUrkM4IUGqqHq66PuVS
    expirationMinutes: 1440
